# CHALLENGE BITACORA 3 Y EJERCICIOS

## CHALLENGE
Googlea qué es un Diccionario. Crea un ejemplo en un notebook vacío.

**Diccionario**: Un Diccionario es una estructura de datos y un tipo de dato en Python con características especiales que nos permite almacenar cualquier tipo de valor como enteros, cadenas, listas e incluso otras funciones. Estos diccionarios nos permiten además identificar cada elemento por una clave (Key).

In [2]:
palabras_A = {"Arroz" : "Grano", "Aveja": "Animal", "Asterico": "simbolo", "Arbol": "planta"}
type(palabras_A)

dict

In [3]:
palabras_A["Arroz"]

'Grano'

**Ejercicio:** investiga y crea ejemplos con las siguientes funciones
* `np.linspace`. Presta particular atención a cómo se diferencia de `np.arange`.
* `np.zeros` y `np.ones`

In [8]:
import numpy as np

In [8]:
np.linspace( 0, 2, 9 ) # 9 números entre el 0 y el 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.arange( 10, 30, 5 ) # números del 10 al 30 de 5 en 5

array([10, 15, 20, 25])

In [10]:
np.zeros((3, 4)) # 3 arrays de a 4 números cada uno en 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((1, 2, 4)) # 1 set de 2 arrays de 4 números en 1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Ejercitación

**Ejercicio 1**: Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: `linspace`

In [12]:
np.linspace( 0, 9, 100 )

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

In [4]:
9/100

0.09

**Ejercicio 2:** crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos.

In [20]:
arreglo1D = np.zeros((20))
arreglo1D

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [22]:
arreglo1D[0, :15] = 1
arreglo1D

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Ejercicio 3:** crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales del 0 al 24.

In [23]:
arreglo1D = np.zeros((50))
arreglo1D

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
arreglo1D[:25] = np.arange(25)
arreglo1D

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**Ejercicio 4:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la segunda columna por los números 1, 2 y 3 respectivamente. Es decir, crear la siguiente matriz:

```
0 1 0 
0 2 0
0 3 0
```

In [53]:
arreglo2D = np.zeros((3, 3))
arreglo2D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
arreglo2D[:1, 1:2] = 1
arreglo2D[1:2, 1:2] = 2
arreglo2D[2:3, 1:2] = 3
arreglo2D

array([[0., 1., 0.],
       [0., 2., 0.],
       [0., 3., 0.]])

**Ejercicio 5:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 
0 1 0
0 0 1
```

In [57]:
arreglo2D = np.zeros((3, 3))
arreglo2D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
arreglo2D[:1, :1] = 1
arreglo2D[1:2, 1:2] = 1
arreglo2D[2:3, 2:3] = 1
arreglo2D

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Ejercicio 6:** crear un arreglo 2D de 100 filas y 100 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 ... 0 0 0 
0 1 0 ... 0 0 0
0 0 1 ... 0 0 0
...  
0 0 0 ... 1 0 0
0 0 0 ... 0 1 0
0 0 0 ... 0 0 1
```

In [74]:
arreglo2D = np.zeros((100, 100))
arreglo2D

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
arreglo2D = np.eye(10,10, k=2)
arreglo2D

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
np.identity(10)*5.6

array([[5.6, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 5.6, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 5.6, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 5.6, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 5.6, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 5.6, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 5.6, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 5.6, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5.6, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 5.6]])

**Extra:** ¿Qué tipo de dato está usando NumPy cuando crea los arreglos?¿Y si queremos cambiarle el tipo de dato, por ejemplo a `int`? Googlear "numpy astype". ¿Qué pasa si usamos `astype(bool)`?

In [95]:
arr1 = np.array([[1,2.4,3.5,4],[5,6,7,8]])
arr1 = arr1 = arr1.astype('int32') 
arr1.dtype

dtype('int32')

El tipo de dato que usa NumPy cuando crea los arreglos depende del tipo de dato que se ingrese en los arreglos, es decir si es tipo int o float, y se escoge el más completo. Para cambiarle el tipo de dato al arreglo se usa astype()

In [96]:
arr1 = arr1 = arr1.astype('bool') 
arr1.dtype

dtype('bool')